language: go

os:
  - linux
  - osx
  
env:
    - GIMME_OS=linux GIMME_ARCH=amd64
    - GIMME_OS=darwin GIMME_ARCH=amd64
    - GIMME_OS=windows GIMME_ARCH=amd64

matrix:
  allow_failures:
    - os: osx

sudo: required

install:
  - brew install gimme
  - gimme 1.5
  - cat ~/.gimme/envs/go1.5.env >> ~/.bashrc 
  - go get -v golang.org/x/exp/ebnf
  - make build
script:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - make test
#  - goveralls -coverprofile=coverage.txt -service=travis-ci
before_install:
  - sudo pip install codecov
after_success:
  codecov
notifications:
  email:
    - tiago.natel@neoway.com.br
